---
title: "Writing_Function"
output: github_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## get started 

We're going to write some functions. 

```{r}
x = rnorm(n = 30, mean = 4, sd = 2.3)
x_again = rnorm(n = 20, mean = 6, sd = 0.3)
y = rnorm(n = 30, mean = 24, sd = 2.3)

(x - mean(x)) / sd(x)
(x_again - mean(x_again)) / sd(x_again)
```

Now a function.

```{r}
z_score = function(x_arg) {
## condition execution
  if (!is.numeric(x_arg)){
    stop( "x should be numeric")
    } else if (length(x_arg) < 3){
    stop("x should be longer than 3")
    }
  
  (x - mean(x_arg)) /  sd(x_arg)
  
}
```

Try out the function. 

```{r, error = TRUE}
z_score(x_arg = y)
z_score(x = 3)
z_score(x = c(TRUE,TRUE,FALSE,TRUE))
## convert them to numeric
z_score(x = "my name is jeff")
z_score(x = iris)  ## iris is a dataframe 

```

## multiple outputs 

```{r}
mean_and_sd = function(input_x){
  if (!is.numeric(input_x)){
    stop( "x should be numeric")
    } else if (length(input_x) < 3){
    stop("x should be longer than 3")
    }
  ## into a data frame with tibble
    list(
    mean_input = mean(input_x),
    sd_input = sd(input_x),
    z_score = (input_x - mean(input_x))/sd(input_x)
    ) 
}
```

test this function 

```{r}
mean_and_sd(input_x = y)
```

## Multiple inputs

```{r}



```






 
 